required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/cloudfoundry/bosh-davcli"
  version = "0.0.23"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-init"
  version = "0.0.103"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/gosigar"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/yagnats"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal/go-smtpd"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "github.com/masterzen/winrm"

[[override]]
  branch = "master"
  name = "github.com/masterzen/azure-sdk-for-go"

[[override]]
  name = "github.com/masterzen/simplexml"
  revision = "95ba30457eb1121fa27753627c774c7cd4e90083"

[[override]]
  name = "github.com/ChrisTrenkamp/goxpath"
  branch = "master"

[[override]]
  name = "golang.org/x/crypto"
  revision = "12dd70caea0268ac0d6c2707d0611ef601e7c64e"
